version: 2

sources:
  - name: coingecko # Source name
    database: silken-apex-477018-d4   # GCP Project ID
    schema: btc  # BigQuery Dataset
    tables: 
      - name: raw_coingecko_bitcoin   # Table name
        description: "Raw data imported from CoinGecko API."  
        columns:
          - name: date
            description: "The date of the bitcoin price record."
          - name: price
            description: "The price of bitcoin in USD on the given date."